### Write a NumPy program to implement following operation
* to convert a list of numeric values into a one-dimensional NumPy array

In [1]:
import numpy as np

In [2]:
list=[10,11,23,29]

In [3]:
a=np.array(list)

In [4]:
print(a)

[10 11 23 29]


* To create a 3x3 matrix with values ranging from 2 to 10

In [5]:
b=np.arange(2,11)

In [6]:
b

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
b=b.reshape(3,3)

In [8]:
print(b)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


* to append values at the end of an array 

In [9]:
c = np.append(a, [11,12])
print(c)

[10 11 23 29 11 12]


* to create another shape from an array without changing its data(3*2 to 2*3) 

In [10]:
arr = np.array([[1,2],
               [3,4],
               [5,6]])
print(arr)

[[1 2]
 [3 4]
 [5 6]]


In [12]:
arr = arr.reshape(2,3)
print(arr)

[[1 2 3]
 [4 5 6]]
