
* to split an array of 14 elements into 3 arrays, each with 2, 4, and 8 elements in the original order

import numpy as np

In [6]:
array=np.arange(1,15)

In [7]:
print("Original array")
print(array)

Original array
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [12]:
array1,array2,array3= np.split(array,[2,6])

In [14]:
print("2 Elemetns=",array1)
print("4 Elements=",array2)
print("8 Elements=",array3)

2 Elemetns= [1 2]
4 Elements= [3 4 5 6]
8 Elements= [ 7  8  9 10 11 12 13 14]


* to stack arrays horizontally (column wise) 

In [6]:
import numpy as np

In [7]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1=np.array([[10,11,12],[13,14,15],[16,17,18]])

In [16]:
stack=np.hstack((arr,arr1))

In [19]:
print("Horizontally stack\n",stack)

Horizontally stack
 [[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]
